massimo_blog:
    resource: "@MassimoBlogBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

#routes de mon blog
blog:
    resource: "@MassimoBlogBundle/Controller/"
    type:     annotation