<?php

namespace Massimo\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
	public function getArticles()
	{
		$qd = $this->createQueryBuilder('a')
		
		           ->leftJoin('a.image','i')
		           ->addSelect('i')
		
		           ->leftJoin('a.categories','c')
		           ->addSelect('c')
		           
		           ->where('a.publication = :val')
		           ->setParameter('val', 1)
		           
		           ->orderBy('a.datecreation', "DESC" );

		$query = $qd->getQuery();
		
		return $query->getResult();
	}
	
	
	
	public function getArticle( $myID)
	{
		$myID = (int) $myID;
		
		$qd = $this->createQueryBuilder('a')
	
		->leftJoin('a.image','i')
		->addSelect('i')
	
		->leftJoin('a.categories','c')
		->addSelect('c')
		 
		->where('a.publication = :val AND a.id = :searchID')
		->setParameter('val', 1)
		->setParameter('searchID', $myID)
		 
		->orderBy('a.datecreation', "DESC" );
	
		$query = $qd->getQuery();
	
		return $query->getOneOrNullResult();
	}
}
